// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ordem_Servico.Infra.Migrations
{
    [DbContext(typeof(OrdemServicoContext))]
    partial class OrdemServicoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ordem_Servico.Domain.Finalizacao", b =>
                {
                    b.Property<int>("FinalizacaoID")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataFinalizacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FinalizacaoID");

                    b.ToTable("Finalizacao", (string)null);
                });

            modelBuilder.Entity("Ordem_Servico.Domain.OrdemServico", b =>
                {
                    b.Property<int>("OrdemServicoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int>("TecnicoID")
                        .HasColumnType("int");

                    b.HasKey("OrdemServicoID");

                    b.ToTable("OrdemServico", (string)null);
                });

            modelBuilder.Entity("Ordem_Servico.Domain.Finalizacao", b =>
                {
                    b.HasOne("Ordem_Servico.Domain.OrdemServico", "OrdemServico")
                        .WithOne("Finalizacao")
                        .HasForeignKey("Ordem_Servico.Domain.Finalizacao", "FinalizacaoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("Ordem_Servico.Domain.OrdemServico", b =>
                {
                    b.Navigation("Finalizacao");
                });
#pragma warning restore 612, 618
        }
    }
}
